import { Truck, ShoppingBag, Leaf, Building2, Scale, Database } from 'lucide-react';

export const categories = {
  all: { label: 'All', id: 'all' },
  product: { label: 'Product Engineering', id: 'product' },
  backend: { label: 'Backend', id: 'backend' },
  ai: { label: 'AI / ML', id: 'ai' },
  saas: { label: 'SaaS', id: 'saas' },
  data: { label: 'Data Engineering', id: 'data' },
};

export const projects = [
  { id: 'platdel', slug: 'plat-del', number: '01', title: 'PLAT-DEL®', subtitle: 'Production Logistics & Delivery Platform', year: '2025', market: 'Kenya', flag: '🇰🇪', icon: Truck, image: '/projects/plat-del.svg', category: ['product', 'backend'], status: 'Production', summary: 'A production-oriented logistics ecosystem connecting customers, vendors and delivery operations across the Kenyan market.', description: 'Building production logistics infrastructure for the Kenyan market. A multi-sided logistics ecosystem connecting customers, vendors, riders and administrators through automated workflows.', problem: 'Traditional delivery operations require coordination between customers, vendors, riders and administrators.', solution: 'Built a multi-sided logistics platform connecting these actors through automated workflows.', role: 'Designed and built the backend architecture, APIs, database schema, authentication system and production deployment pipeline.', engineering: ['Designed and implemented backend APIs using Laravel', 'Built role-based workflows for customers, vendors, riders and administrators', 'Designed relational database schemas, migrations and indexes', 'Implemented authentication and authorization (RBAC)', 'Optimized API/database performance with caching', 'Deployed and maintained production on Linux/Nginx'], challenge: 'The platform experienced high API traffic during initial page loads.', technologies: { backend: ['Laravel', 'PHP', 'REST APIs'], frontend: ['React', 'TypeScript'], data: ['MySQL', 'Redis'], infrastructure: ['Nginx', 'Docker'] }, stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL', 'Redis'], capabilities: ['LOGISTICS', 'BACKEND ENGINEERING', 'API ARCHITECTURE', 'DELIVERY OPERATIONS'], actors: ['Customers', 'Vendors', 'Riders', 'Administrators'], github: 'https://github.com/Jigishas', demo: null, featured: true, priority: 1, layout: 'right' },
  { id: 'kidu', slug: 'kidu-errands', number: '02', title: 'Kidu Errands', subtitle: 'On-Demand Errand & Delivery Platform', year: '2025', market: 'Tanzania', flag: '🇹🇿', icon: ShoppingBag, image: '/projects/kidu-errands.svg', category: ['product', 'backend'], status: 'Production', summary: 'An on-demand errand marketplace connecting customers with service providers for delivery and local services in Tanzania.', description: 'Adapting on-demand logistics technology for the Tanzanian market. An errand marketplace connecting customers with service providers.', problem: 'Coordinating errands and local deliveries in Tanzanian markets involves connecting customers with reliable service providers.', solution: 'Built an on-demand errand platform with service discovery, location-based matching and role-based workflows.', role: 'Engineered the backend architecture, API design, database schema and role-based access control.', engineering: ['Designed backend APIs for the errand marketplace', 'Built role-based workflows for customers, vendors and riders', 'Implemented location-based service discovery', 'Designed database schemas for order and service management', 'Integrated authentication and authorization', 'Built notification system for order updates'], challenge: 'Adapting the logistics architecture to support both errand services and delivery workflows.', technologies: { backend: ['Laravel', 'PHP', 'REST APIs'], frontend: ['React', 'TypeScript'], data: ['MySQL'], infrastructure: ['Nginx'] }, stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL'], capabilities: ['ERRAND MARKETPLACE', 'LOCATION SERVICES', 'ROLE-BASED WORKFLOWS'], actors: ['Customers', 'Vendors', 'Riders'], github: 'https://github.com/Jigishas', demo: null, featured: true, priority: 2, layout: 'left' },
  { id: 'healthycoffee', slug: 'healthy-coffee', number: '03', title: 'HealthyCoffee', subtitle: 'AI-Powered Agricultural Intelligence Platform', year: '2025', market: null, flag: '🌱', icon: Leaf, image: '/projects/healthy-coffee-logo.jpg', category: ['ai', 'product'], status: 'Live', summary: 'AI solving a practical agricultural problem — helping coffee farmers detect diseases and nutrient deficiencies from leaf images.', description: 'An end-to-end AI platform combining computer vision with a Progressive Web App. Farmers capture leaf images via camera or upload.', problem: 'Coffee farmers in developing regions often lack access to agricultural experts who can diagnose plant diseases.', solution: 'Built an end-to-end AI platform combining computer vision with a Progressive Web App.', role: 'Built the full-stack application — Flask API backend, React 19 frontend with PWA capabilities, camera integration.', engineering: ['Built a React 19 frontend with PWA capabilities', 'Developed Flask API backend serving optimized PyTorch models', 'Trained EfficientNet models for coffee leaf classification', 'Implemented camera integration for real-time leaf capture', 'Deployed backend on Render with cold-start optimization', 'Configured CORS for multi-origin production'], challenge: 'Deploying ML models within free-tier infrastructure constraints required model optimization.', technologies: { ai: ['Python', 'PyTorch', 'EfficientNet', 'Computer Vision'], backend: ['Flask', 'Gunicorn'], frontend: ['React 19', 'Vite', 'PWA', 'Tailwind CSS'], infrastructure: ['Render', 'Vercel'] }, stack: ['React 19', 'Flask', 'Python', 'PyTorch', 'PWA'], capabilities: ['COMPUTER VISION', 'MACHINE LEARNING', 'AGRICULTURAL AI', 'OFFLINE-FIRST', 'PWA'], detections: ['Coffee Leaf Rust', 'Cercospora Leaf Spot', 'Nitrogen Deficiency', 'Iron Deficiency', 'Healthy Leaves'], github: 'https://github.com/Jigishas/Healthycoffee', demo: 'https://healthycoffee.vercel.app', featured: true, priority: 3, layout: 'full' },
  { id: 'coppins', slug: 'coppins', number: '04', title: 'Coppins', subtitle: 'Multi-Role Property Management Platform', year: '2025', market: null, flag: '🏢', icon: Building2, image: '/projects/coppins.svg', category: ['saas', 'backend'], status: 'In Development', summary: 'A rental management platform connecting property owners, caretakers and tenants through role-based workflows.', description: 'Designing a multi-role business platform with complex authorization and workflows.', problem: 'Property managers juggle tenants, units, leases and payments across spreadsheets and chat threads.', solution: 'Designed a SaaS property management platform with multi-user workflows and organization-level role-based permissions.', role: 'Architected the multi-role data model, built backend services, implemented RBAC and designed dashboard interfaces.', engineering: ['Designed multi-user workflow models with RBAC', 'Built backend services for properties, tenants and tenancies', 'Modeled relational data with migrations and indexes', 'Implemented authentication and authorization', 'Engineered dashboard views for owners and managers'], challenge: 'Designing a data model that supports multiple property owners and shared staff roles.', technologies: { backend: ['Laravel', 'PHP', 'REST APIs'], frontend: ['React', 'TypeScript', 'Tailwind CSS'], data: ['MySQL'], infrastructure: [] }, stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL'], capabilities: ['MULTI-ROLE RBAC', 'PROPERTY MANAGEMENT', 'SAAS ARCHITECTURE'], actors: ['Property Owners', 'Caretakers', 'Tenants'], github: 'https://github.com/Jigishas', demo: null, featured: false, priority: 4 },
  { id: 'justicehub', slug: 'justice-hub', number: '05', title: 'Justice Hub', subtitle: 'Digital Legal Information Platform', year: '2024', market: null, flag: '⚖️', icon: Scale, image: '/projects/justice-hub-logo.jpg', category: ['product'], status: 'Live', summary: 'Using software engineering to improve access to structured legal information and educational resources.', description: 'A full-stack platform providing legal education resources, search capabilities and community engagement.', problem: 'Access to structured legal information and educational resources is limited for many communities.', solution: 'Built a full-stack platform with user authentication, a curated resource library and real-time search.', role: 'Built the complete full-stack application — React frontend, Node.js/Express API, MongoDB data models.', engineering: ['Built a React 19 frontend with Vite, Tailwind CSS and Radix UI', 'Developed Node.js/Express REST API with JWT authentication', 'Designed MongoDB data models with Mongoose', 'Implemented real-time search across content types', 'Configured Docker and Docker Compose for containerized deployment', 'Set up GitHub Actions CI/CD pipeline'], challenge: 'Designing a flexible content management system that supports multiple content types.', technologies: { backend: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'JWT'], frontend: ['React 19', 'Vite', 'Tailwind CSS', 'Radix UI'], infrastructure: ['Docker', 'Docker Compose', 'Vercel'] }, stack: ['React 19', 'Node.js', 'Express', 'MongoDB', 'Docker'], capabilities: ['INFORMATION MANAGEMENT', 'SEARCH & DISCOVERY', 'FULL-STACK', 'CONTAINERIZED DEPLOYMENT'], github: 'https://github.com/Jigishas/Justice-Hub', demo: 'https://justice-hub-delta.vercel.app', featured: false, priority: 5 },
  { id: 'dataengineering', slug: 'data-engineering', number: '06', title: 'Data Engineering Pipeline', subtitle: 'ETL & Workflow Orchestration', year: '2025', market: null, flag: '📊', icon: Database, image: '/projects/data-engineering.svg', category: ['data'], status: 'Completed', summary: 'Production-ready data pipelines with Apache Airflow for ETL workflows and data transformation.', description: 'Building data pipeline infrastructure using Apache Airflow with Docker Compose orchestration.', problem: 'Organizations need reliable, scheduled data pipelines to extract data from multiple sources.', solution: 'Built data pipeline infrastructure using Apache Airflow with Docker Compose orchestration.', role: 'Designed and implemented the data pipeline architecture, DAGs, ETL workflows and containerized deployment.', engineering: ['Built Apache Airflow DAGs for workflow orchestration', 'Designed ETL pipelines for data extraction and transformation', 'Containerized deployment with Docker Compose', 'Implemented data transformation and scheduling automation', 'Configured Airflow for production-ready pipeline management'], challenge: 'Designing reliable data pipelines that handle scheduling, retries and dependencies.', technologies: { data: ['Python', 'Apache Airflow', 'SQL', 'ETL'], infrastructure: ['Docker', 'Docker Compose'], concepts: ['Data Pipelines', 'Workflow Orchestration', 'Scheduling'] }, stack: ['Python', 'Apache Airflow', 'SQL', 'Docker', 'Docker Compose'], capabilities: ['ETL PIPELINES', 'WORKFLOW ORCHESTRATION', 'DATA TRANSFORMATION', 'AUTOMATION'], github: 'https://github.com/Jigishas/Airflow-ETL', demo: null, featured: false, priority: 6 },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const secondaryProjects = projects.filter((p) => !p.featured);
