import {
  Truck,
  ShoppingBag,
  Leaf,
  Building2,
  Scale,
  Database,
} from 'lucide-react';

export const categories = {
  logistics: { label: 'Logistics & Delivery', color: 'bg-blue-500/10 text-blue-600 border-blue-500/30' },
  ai: { label: 'AI & Machine Learning', color: 'bg-violet-500/10 text-violet-600 border-violet-500/30' },
  saas: { label: 'SaaS & Business Systems', color: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/30' },
  social: { label: 'Social Impact', color: 'bg-amber-500/10 text-amber-600 border-amber-500/30' },
  data: { label: 'Data Engineering', color: 'bg-rose-500/10 text-rose-600 border-rose-500/30' },
};

export const projects = [
  {
    id: 'platdel',
    number: '01',
    title: 'PLAT-DEL®',
    tagline: 'Production Logistics & Delivery Platform',
    market: 'Kenya',
    flag: '🇰🇪',
    icon: Truck,
    category: 'logistics',
    status: 'Production',
    description: 'Building production logistics infrastructure for the Kenyan market. A multi-sided logistics ecosystem connecting customers, vendors, riders and administrators through automated workflows.',
    problem: 'Traditional delivery operations require coordination between customers, vendors, riders and administrators, with manual hand-offs and little visibility across the delivery lifecycle.',
    solution: 'Built a multi-sided logistics platform connecting these actors through automated workflows — with role-based access, order management, parcel tracking and administrative oversight.',
    engineering: [
      'Designed and implemented backend APIs using Laravel',
      'Built role-based workflows for customers, vendors, riders and administrators',
      'Designed relational database schemas, migrations and indexes',
      'Implemented authentication and authorization (RBAC)',
      'Optimized API/database performance with caching',
      'Integrated the React frontend with REST APIs',
      'Deployed and maintained production on Linux/Nginx',
    ],
    challenge: 'The platform experienced high API traffic during initial page loads. I investigated request patterns, applied caching strategies, optimized API queries and reduced unnecessary frontend requests.',
    technologies: {
      backend: ['Laravel', 'PHP', 'REST APIs'],
      frontend: ['React', 'TypeScript'],
      data: ['MySQL', 'Redis'],
      infrastructure: ['Nginx', 'Docker', 'Linux'],
    },
    stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL', 'Redis', 'Nginx', 'Docker'],
    capabilities: ['Delivery management', 'Logistics workflows', 'Vendor management', 'Rider management', 'Customer ordering', 'Parcel delivery', 'Order management', 'Real-time workflows', 'Payments', 'Notifications', 'API architecture', 'Authentication', 'Role-based access', 'Database architecture', 'Performance optimization', 'Production deployment'],
    actors: ['Customers', 'Vendors', 'Riders', 'Administrators'],
    github: 'https://github.com/Jigishas',
    demo: null,
    featured: true,
    priority: 1,
  },
  {
    id: 'kidu',
    number: '02',
    title: 'Kidu Errands',
    tagline: 'On-Demand Errand & Delivery Platform',
    market: 'Tanzania',
    flag: '🇹🇿',
    icon: ShoppingBag,
    category: 'logistics',
    status: 'Production',
    description: 'Adapting on-demand logistics technology for the Tanzanian market. An errand marketplace connecting customers with service providers for delivery and local services.',
    problem: 'Coordinating errands and local deliveries in Tanzanian markets involves connecting customers with reliable service providers, managing location-based services and handling payments across multiple parties.',
    solution: 'Built an on-demand errand platform with service discovery, location-based matching, role-based workflows for customers, vendors and riders, and integrated payment processing.',
    engineering: [
      'Designed backend APIs for the errand marketplace',
      'Built role-based workflows for customers, vendors and riders',
      'Implemented location-based service discovery',
      'Designed database schemas for order and service management',
      'Integrated authentication and authorization',
      'Built notification system for order updates',
    ],
    challenge: 'Adapting the logistics architecture to support both errand services and delivery workflows while maintaining clear separation of concerns and consistent API design.',
    technologies: {
      backend: ['Laravel', 'PHP', 'REST APIs'],
      frontend: ['React', 'TypeScript'],
      data: ['MySQL'],
      infrastructure: ['Nginx'],
    },
    stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL', 'Nginx'],
    capabilities: ['Errand marketplace', 'Delivery services', 'Vendor ecosystem', 'Customer experience', 'Rider workflows', 'Location-based services', 'Order management', 'Service discovery', 'Payments', 'Notifications', 'Backend APIs', 'Authentication', 'Role-based workflows', 'Database architecture'],
    actors: ['Customers', 'Vendors', 'Riders'],
    github: 'https://github.com/Jigishas',
    demo: null,
    featured: true,
    priority: 2,
  },
  {
    id: 'healthycoffee',
    number: '03',
    title: 'HealthyCoffee',
    tagline: 'AI-Powered Agricultural Intelligence Platform',
    market: null,
    flag: '🌱',
    icon: Leaf,
    category: 'ai',
    status: 'Live',
    description: 'AI + Software Engineering + Real-world Impact. A machine learning platform that helps coffee farmers detect diseases and nutrient deficiencies from leaf images.',
    problem: 'Coffee farmers in developing regions often lack access to agricultural experts who can diagnose plant diseases and nutrient deficiencies early, leading to reduced crop yields.',
    solution: 'Built an end-to-end AI platform combining computer vision with a Progressive Web App. Farmers capture leaf images via camera or upload, and the system returns disease/deficiency classifications with recommendations.',
    engineering: [
      'Built a React 19 frontend with PWA capabilities for offline use',
      'Developed Flask API backend serving optimized PyTorch models',
      'Trained EfficientNet models for coffee leaf classification',
      'Implemented camera integration for real-time leaf capture',
      'Deployed backend on Render with cold-start optimization',
      'Configured CORS for multi-origin production communication',
      'Implemented backend health monitoring with auto-retry',
    ],
    challenge: 'Deploying ML models within free-tier infrastructure constraints required model optimization (under 500ms inference, under 2GB RAM), implementing keep-alive pings to prevent cold starts, and building a health monitoring system with visual status indicators and auto-retry on the frontend.',
    technologies: {
      ai: ['Python', 'PyTorch', 'EfficientNet', 'Computer Vision'],
      backend: ['Flask', 'Gunicorn'],
      frontend: ['React 19', 'Vite', 'PWA', 'Tailwind CSS'],
      infrastructure: ['Render', 'Vercel', 'GitHub Actions'],
    },
    stack: ['React 19', 'Vite', 'Flask', 'Python', 'PyTorch', 'EfficientNet', 'PWA', 'Tailwind CSS', 'Render', 'Vercel'],
    capabilities: ['Machine Learning', 'Computer Vision', 'Agricultural intelligence', 'Coffee leaf analysis', 'Disease detection', 'Nutrient deficiency detection', 'Image processing', 'ML model deployment', 'PWA architecture', 'Offline-first capabilities', 'Camera integration', 'Real-time analysis', 'AI explanations', 'Backend health monitoring'],
    detections: ['Coffee Leaf Rust', 'Cercospora Leaf Spot', 'Nitrogen deficiency', 'Iron deficiency', 'Healthy leaves'],
    github: 'https://github.com/Jigishas/Healthycoffee',
    demo: 'https://healthycoffee.vercel.app',
    featured: true,
    priority: 3,
  },
  {
    id: 'coppins',
    number: '04',
    title: 'Coppins',
    tagline: 'Multi-Role Property Management Platform',
    market: null,
    flag: '🏢',
    icon: Building2,
    category: 'saas',
    status: 'In Development',
    description: 'Designing a multi-role business platform with complex authorization and workflows. A SaaS property management system with distinct portals for owners, caretakers and tenants.',
    problem: 'Property managers juggle tenants, units, leases and payments across spreadsheets and chat threads, with no single source of truth and no clear role-based access to property data.',
    solution: 'Designed a SaaS property management platform with multi-user workflows, organization-level role-based permissions and records for properties, tenants and tenancies.',
    engineering: [
      'Designed multi-user workflow models with RBAC',
      'Built backend services for properties, tenants and tenancies',
      'Modeled relational data with migrations and indexes',
      'Implemented authentication and authorization',
      'Engineered dashboard views for owners and managers',
    ],
    challenge: 'Designing a data model that supports multiple property owners, shared staff roles and permission levels without leaking data across organizations.',
    technologies: {
      backend: ['Laravel', 'PHP', 'REST APIs'],
      frontend: ['React', 'TypeScript', 'Tailwind CSS'],
      data: ['MySQL'],
      infrastructure: [],
    },
    stack: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL', 'Tailwind CSS'],
    capabilities: ['Property management', 'Rental management', 'Owner portal', 'Caretaker portal', 'Tenant portal', 'Role-based access control', 'Authentication', 'Property/unit management', 'Tenant management', 'Rental workflows', 'Dashboards', 'Database architecture', 'API architecture'],
    actors: ['Property Owners', 'Caretakers', 'Tenants'],
    github: 'https://github.com/Jigishas',
    demo: null,
    featured: false,
    priority: 4,
  },
  {
    id: 'justicehub',
    number: '05',
    title: 'Justice Hub',
    tagline: 'Digital Legal Information Platform',
    market: null,
    flag: '⚖️',
    icon: Scale,
    category: 'social',
    status: 'Live',
    description: 'Using software engineering to improve access to structured information. A full-stack platform providing legal education resources, search capabilities and community engagement.',
    problem: 'Access to structured legal information and educational resources is limited for many communities, making it difficult to understand rights and navigate legal systems.',
    solution: 'Built a full-stack platform with user authentication, a curated resource library, real-time search across content types, and actionable initiatives for social engagement.',
    engineering: [
      'Built a React 19 frontend with Vite, Tailwind CSS and Radix UI',
      'Developed Node.js/Express REST API with JWT authentication',
      'Designed MongoDB data models with Mongoose',
      'Implemented real-time search across content types',
      'Configured Docker and Docker Compose for containerized deployment',
      'Set up GitHub Actions CI/CD pipeline',
    ],
    challenge: 'Designing a flexible content management system that supports multiple content types (articles, videos, podcasts, books, toolkits) with a unified search experience, while maintaining clean API design and containerized deployment.',
    technologies: {
      backend: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'JWT'],
      frontend: ['React 19', 'Vite', 'Tailwind CSS', 'Radix UI', 'Framer Motion'],
      infrastructure: ['Docker', 'Docker Compose', 'GitHub Actions', 'Vercel'],
    },
    stack: ['React 19', 'Vite', 'Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'JWT', 'Tailwind CSS', 'Docker', 'Vercel'],
    capabilities: ['Information management', 'Legal information', 'Search and discovery', 'Data organization', 'Full-stack development', 'Backend APIs', 'User authentication', 'Dashboard', 'Educational resources', 'Real-time search', 'Containerized deployment', 'CI/CD'],
    github: 'https://github.com/Jigishas/Justice-Hub',
    demo: 'https://justice-hub-delta.vercel.app',
    featured: false,
    priority: 5,
  },
  {
    id: 'dataengineering',
    number: '06',
    title: 'Data Engineering Pipeline',
    tagline: 'ETL & Workflow Orchestration',
    market: null,
    flag: '📊',
    icon: Database,
    category: 'data',
    status: 'Completed',
    description: 'I understand data engineering beyond application development. Building production-ready data pipelines with Apache Airflow for ETL workflows and data transformation.',
    problem: 'Organizations need reliable, scheduled data pipelines to extract data from multiple sources, transform it through business rules, and load it into target systems for analysis.',
    solution: 'Built data pipeline infrastructure using Apache Airflow with Docker Compose orchestration, implementing ETL workflows for data extraction, transformation and scheduling.',
    engineering: [
      'Built Apache Airflow DAGs for workflow orchestration',
      'Designed ETL pipelines for data extraction and transformation',
      'Containerized deployment with Docker Compose',
      'Implemented data transformation and scheduling automation',
      'Configured Airflow for production-ready pipeline management',
    ],
    challenge: 'Designing reliable data pipelines that handle scheduling, retries, dependencies between tasks, and monitoring while maintaining clean separation of extraction, transformation and loading concerns.',
    technologies: {
      data: ['Python', 'Apache Airflow', 'SQL', 'ETL'],
      infrastructure: ['Docker', 'Docker Compose'],
      concepts: ['Data Pipelines', 'Workflow Orchestration', 'Data Transformation', 'Scheduling'],
    },
    stack: ['Python', 'Apache Airflow', 'SQL', 'Docker', 'Docker Compose', 'ETL', 'Data Pipelines'],
    capabilities: ['Python', 'Apache Airflow', 'SQL', 'ETL', 'Data pipelines', 'Workflow orchestration', 'Data transformation', 'Scheduling', 'Automation', 'Docker', 'Data extraction', 'Production pipelines'],
    github: 'https://github.com/Jigishas/Airflow-ETL',
    demo: null,
    featured: false,
    priority: 6,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const selectedProjects = projects.filter((p) => !p.featured && p.priority <= 5);
export const dataEngineeringProject = projects.find((p) => p.category === 'data');